CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "Clubs" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Code" character varying(10) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "IsActive" boolean NOT NULL,
    "Address" character varying(200),
    "City" character varying(100),
    "Country" character varying(100),
    "Email" character varying(100),
    "PhoneNumber" character varying(20),
    "Website" character varying(200),
    "LogoUrl" character varying(200),
    "FoundedDate" timestamp with time zone,
    CONSTRAINT "PK_Clubs" PRIMARY KEY ("Id")
);

CREATE TABLE "Commissions" (
    "Id" uuid NOT NULL,
    "Nom" character varying(100) NOT NULL,
    "Description" character varying(200) NOT NULL,
    CONSTRAINT "PK_Commissions" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "ProfilePictureUrl" character varying(200),
    "JoinedDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "PrimaryClubId" uuid,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_Clubs_PrimaryClubId" FOREIGN KEY ("PrimaryClubId") REFERENCES "Clubs" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Mandats" (
    "Id" uuid NOT NULL,
    "Annee" integer NOT NULL,
    "DateDebut" timestamp with time zone NOT NULL,
    "DateFin" timestamp with time zone NOT NULL,
    "Description" character varying(200),
    "EstActuel" boolean NOT NULL,
    "ClubId" uuid NOT NULL,
    CONSTRAINT "PK_Mandats" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Mandats_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CommissionsClub" (
    "Id" uuid NOT NULL,
    "CommissionId" uuid NOT NULL,
    "ClubId" uuid NOT NULL,
    "EstActive" boolean NOT NULL,
    "NotesSpecifiques" character varying(500),
    "DateCreation" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CommissionsClub" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CommissionsClub_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CommissionsClub_Commissions_CommissionId" FOREIGN KEY ("CommissionId") REFERENCES "Commissions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserClubs" (
    "Id" uuid NOT NULL,
    "UserId" text NOT NULL,
    "ClubId" uuid NOT NULL,
    "JoinedDate" timestamp with time zone NOT NULL,
    "Position" text NOT NULL,
    CONSTRAINT "PK_UserClubs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClubs_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserClubs_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MembresCommission" (
    "Id" uuid NOT NULL,
    "EstResponsable" boolean NOT NULL,
    "DateNomination" timestamp with time zone NOT NULL,
    "DateDemission" timestamp with time zone,
    "EstActif" boolean NOT NULL,
    "Commentaires" character varying(500),
    "CommissionClubId" uuid NOT NULL,
    "MembreId" text NOT NULL,
    "MandatId" uuid NOT NULL,
    "ApplicationUserId" text,
    CONSTRAINT "PK_MembresCommission" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MembresCommission_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id"),
    CONSTRAINT "FK_MembresCommission_AspNetUsers_MembreId" FOREIGN KEY ("MembreId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MembresCommission_CommissionsClub_CommissionClubId" FOREIGN KEY ("CommissionClubId") REFERENCES "CommissionsClub" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MembresCommission_Mandats_MandatId" FOREIGN KEY ("MandatId") REFERENCES "Mandats" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_AspNetUsers_PrimaryClubId" ON "AspNetUsers" ("PrimaryClubId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_Clubs_Code" ON "Clubs" ("Code");

CREATE UNIQUE INDEX "IX_Commissions_Nom" ON "Commissions" ("Nom");

CREATE INDEX "IX_CommissionsClub_ClubId" ON "CommissionsClub" ("ClubId");

CREATE UNIQUE INDEX "IX_CommissionsClub_CommissionId_ClubId" ON "CommissionsClub" ("CommissionId", "ClubId");

CREATE UNIQUE INDEX "IX_Mandats_ClubId_Annee" ON "Mandats" ("ClubId", "Annee");

CREATE UNIQUE INDEX "IX_Mandats_ClubId_EstActuel" ON "Mandats" ("ClubId", "EstActuel") WHERE "EstActuel" = true;

CREATE INDEX "IX_MembresCommission_ApplicationUserId" ON "MembresCommission" ("ApplicationUserId");

CREATE UNIQUE INDEX "IX_MembresCommission_CommissionClubId_MembreId_MandatId" ON "MembresCommission" ("CommissionClubId", "MembreId", "MandatId");

CREATE INDEX "IX_MembresCommission_MandatId" ON "MembresCommission" ("MandatId");

CREATE INDEX "IX_MembresCommission_MembreId" ON "MembresCommission" ("MembreId");

CREATE INDEX "IX_UserClubs_ClubId" ON "UserClubs" ("ClubId");

CREATE INDEX "IX_UserClubs_UserId" ON "UserClubs" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250519220316_initialcreate', '9.0.5');

ALTER TABLE "AspNetUsers" ADD "Department" character varying(100);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250521113904_initialcreate1', '9.0.5');

CREATE TABLE "Comites" (
    "Id" uuid NOT NULL,
    "MandatId" uuid NOT NULL,
    CONSTRAINT "PK_Comites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comites_Mandats_MandatId" FOREIGN KEY ("MandatId") REFERENCES "Mandats" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Fonctions" (
    "Id" uuid NOT NULL,
    "NomFonction" character varying(100) NOT NULL,
    CONSTRAINT "PK_Fonctions" PRIMARY KEY ("Id")
);

CREATE TABLE "ComiteMembres" (
    "Id" uuid NOT NULL,
    "ComiteId" uuid NOT NULL,
    "MembreId" text NOT NULL,
    "FonctionId" uuid NOT NULL,
    CONSTRAINT "PK_ComiteMembres" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ComiteMembres_AspNetUsers_MembreId" FOREIGN KEY ("MembreId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ComiteMembres_Comites_ComiteId" FOREIGN KEY ("ComiteId") REFERENCES "Comites" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ComiteMembres_Fonctions_FonctionId" FOREIGN KEY ("FonctionId") REFERENCES "Fonctions" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_ComiteMembres_ComiteId_MembreId_FonctionId" ON "ComiteMembres" ("ComiteId", "MembreId", "FonctionId");

CREATE INDEX "IX_ComiteMembres_FonctionId" ON "ComiteMembres" ("FonctionId");

CREATE INDEX "IX_ComiteMembres_MembreId" ON "ComiteMembres" ("MembreId");

CREATE INDEX "IX_Comites_MandatId" ON "Comites" ("MandatId");

CREATE INDEX "IX_Fonctions_NomFonction" ON "Fonctions" ("NomFonction");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250521211130_initialcreate23', '9.0.5');

ALTER TABLE "Comites" ADD "Nom" character varying(100) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250522123648_initial1', '9.0.5');

CREATE TABLE "TypesReunion" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(100) NOT NULL,
    CONSTRAINT "PK_TypesReunion" PRIMARY KEY ("Id")
);

CREATE TABLE "Reunions" (
    "Id" uuid NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "TypeReunionId" uuid NOT NULL,
    CONSTRAINT "PK_Reunions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reunions_TypesReunion_TypeReunionId" FOREIGN KEY ("TypeReunionId") REFERENCES "TypesReunion" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "InvitesReunion" (
    "Id" uuid NOT NULL,
    "Nom" character varying(100) NOT NULL,
    "Prenom" character varying(100) NOT NULL,
    "Email" character varying(255),
    "Telephone" character varying(20),
    "Organisation" character varying(200),
    "ReunionId" uuid NOT NULL,
    CONSTRAINT "PK_InvitesReunion" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvitesReunion_Reunions_ReunionId" FOREIGN KEY ("ReunionId") REFERENCES "Reunions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ListesPresence" (
    "Id" uuid NOT NULL,
    "MembreId" text NOT NULL,
    "ReunionId" uuid NOT NULL,
    CONSTRAINT "PK_ListesPresence" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ListesPresence_AspNetUsers_MembreId" FOREIGN KEY ("MembreId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ListesPresence_Reunions_ReunionId" FOREIGN KEY ("ReunionId") REFERENCES "Reunions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrdresDuJour" (
    "Id" uuid NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "ReunionId" uuid NOT NULL,
    CONSTRAINT "PK_OrdresDuJour" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrdresDuJour_Reunions_ReunionId" FOREIGN KEY ("ReunionId") REFERENCES "Reunions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReunionDocuments" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(200) NOT NULL,
    "ReunionId" uuid NOT NULL,
    "Document" bytea NOT NULL,
    CONSTRAINT "PK_ReunionDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReunionDocuments_Reunions_ReunionId" FOREIGN KEY ("ReunionId") REFERENCES "Reunions" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_InvitesReunion_Email" ON "InvitesReunion" ("Email");

CREATE INDEX "IX_InvitesReunion_Nom_Prenom" ON "InvitesReunion" ("Nom", "Prenom");

CREATE INDEX "IX_InvitesReunion_ReunionId" ON "InvitesReunion" ("ReunionId");

CREATE INDEX "IX_ListesPresence_MembreId" ON "ListesPresence" ("MembreId");

CREATE UNIQUE INDEX "IX_ListesPresence_MembreId_ReunionId" ON "ListesPresence" ("MembreId", "ReunionId");

CREATE INDEX "IX_ListesPresence_ReunionId" ON "ListesPresence" ("ReunionId");

CREATE INDEX "IX_OrdresDuJour_ReunionId" ON "OrdresDuJour" ("ReunionId");

CREATE INDEX "IX_ReunionDocuments_Libelle" ON "ReunionDocuments" ("Libelle");

CREATE INDEX "IX_ReunionDocuments_ReunionId" ON "ReunionDocuments" ("ReunionId");

CREATE INDEX "IX_Reunions_Date" ON "Reunions" ("Date");

CREATE INDEX "IX_Reunions_TypeReunionId_Date" ON "Reunions" ("TypeReunionId", "Date");

CREATE UNIQUE INDEX "IX_TypesReunion_Libelle" ON "TypesReunion" ("Libelle");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250526181954_initial3', '9.0.5');

ALTER TABLE "Reunions" ADD "Heure" interval NOT NULL DEFAULT INTERVAL '00:00:00';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250527103621_initial4', '9.0.5');

DROP INDEX "IX_Reunions_Date";

DROP INDEX "IX_Reunions_TypeReunionId_Date";

ALTER TABLE "Reunions" ALTER COLUMN "Heure" TYPE time;

ALTER TABLE "Reunions" ALTER COLUMN "Date" TYPE date;

CREATE INDEX "IX_Reunions_Date_Heure" ON "Reunions" ("Date", "Heure");

CREATE INDEX "IX_Reunions_TypeReunionId" ON "Reunions" ("TypeReunionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250527104531_initial5', '9.0.5');

ALTER TABLE "AspNetUsers" DROP CONSTRAINT "FK_AspNetUsers_Clubs_PrimaryClubId";

ALTER TABLE "UserClubs" DROP COLUMN "Position";

ALTER TABLE "AspNetUsers" DROP COLUMN "Department";

ALTER TABLE "AspNetUsers" RENAME COLUMN "PrimaryClubId" TO "ClubId";

ALTER INDEX "IX_AspNetUsers_PrimaryClubId" RENAME TO "IX_AspNetUsers_ClubId";

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "FK_AspNetUsers_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250527182357_initial6', '9.0.5');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250528120431_initial7', '9.0.5');

CREATE TABLE "Evenements" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(200) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Lieu" character varying(300),
    "Description" character varying(1000),
    "EstInterne" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Evenements" PRIMARY KEY ("Id")
);

CREATE TABLE "EvenementBudgets" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(200) NOT NULL,
    "MontantBudget" numeric(18,2) NOT NULL,
    "MontantRealise" numeric(18,2) NOT NULL DEFAULT 0.0,
    "EvenementId" uuid NOT NULL,
    CONSTRAINT "PK_EvenementBudgets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EvenementBudgets_Evenements_EvenementId" FOREIGN KEY ("EvenementId") REFERENCES "Evenements" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EvenementDocuments" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(200),
    "Document" bytea NOT NULL,
    "DateAjout" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "EvenementId" uuid NOT NULL,
    CONSTRAINT "PK_EvenementDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EvenementDocuments_Evenements_EvenementId" FOREIGN KEY ("EvenementId") REFERENCES "Evenements" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EvenementImages" (
    "Id" uuid NOT NULL,
    "Image" bytea NOT NULL,
    "Description" character varying(500),
    "DateAjout" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "EvenementId" uuid NOT NULL,
    CONSTRAINT "PK_EvenementImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EvenementImages_Evenements_EvenementId" FOREIGN KEY ("EvenementId") REFERENCES "Evenements" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EvenementRecettes" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(200) NOT NULL,
    "Montant" numeric(18,2) NOT NULL,
    "EvenementId" uuid NOT NULL,
    CONSTRAINT "PK_EvenementRecettes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EvenementRecettes_Evenements_EvenementId" FOREIGN KEY ("EvenementId") REFERENCES "Evenements" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_EvenementBudget_EvenementId_Libelle_Unique" ON "EvenementBudgets" ("EvenementId", "Libelle");

CREATE INDEX "IX_EvenementBudgets_EvenementId" ON "EvenementBudgets" ("EvenementId");

CREATE INDEX "IX_EvenementBudgets_Libelle" ON "EvenementBudgets" ("Libelle");

CREATE INDEX "IX_EvenementBudgets_MontantBudget" ON "EvenementBudgets" ("MontantBudget");

CREATE UNIQUE INDEX "IX_EvenementDocument_EvenementId_Libelle_Unique" ON "EvenementDocuments" ("EvenementId", "Libelle");

CREATE INDEX "IX_EvenementDocuments_DateAjout" ON "EvenementDocuments" ("DateAjout");

CREATE INDEX "IX_EvenementDocuments_EvenementId" ON "EvenementDocuments" ("EvenementId");

CREATE INDEX "IX_EvenementDocuments_Libelle" ON "EvenementDocuments" ("Libelle");

CREATE INDEX "IX_EvenementImages_DateAjout" ON "EvenementImages" ("DateAjout");

CREATE INDEX "IX_EvenementImages_Description" ON "EvenementImages" ("Description");

CREATE INDEX "IX_EvenementImages_EvenementId" ON "EvenementImages" ("EvenementId");

CREATE INDEX "IX_EvenementRecettes_EvenementId" ON "EvenementRecettes" ("EvenementId");

CREATE INDEX "IX_EvenementRecettes_Libelle" ON "EvenementRecettes" ("Libelle");

CREATE INDEX "IX_EvenementRecettes_Montant" ON "EvenementRecettes" ("Montant");

CREATE INDEX "IX_Evenements_Date" ON "Evenements" ("Date");

CREATE INDEX "IX_Evenements_Date_EstInterne" ON "Evenements" ("Date", "EstInterne");

CREATE INDEX "IX_Evenements_EstInterne" ON "Evenements" ("EstInterne");

CREATE INDEX "IX_Evenements_Libelle" ON "Evenements" ("Libelle");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250528162926_Evenement', '9.0.5');

DROP INDEX "IX_Commissions_Nom";

DROP INDEX "IX_Clubs_Code";

ALTER TABLE "Clubs" ADD "DateCreation" character varying(50) NOT NULL DEFAULT '2024-01-01';

ALTER TABLE "Clubs" ADD "NumeroClub" character varying(20) NOT NULL DEFAULT 'TEMP';

ALTER TABLE "Clubs" ADD "NumeroTelephone" character varying(20) NOT NULL DEFAULT '+0000000000';

ALTER TABLE "Clubs" ADD "LieuReunion" character varying(200) NOT NULL DEFAULT 'Lieu à définir';

ALTER TABLE "Clubs" ADD "ParrainePar" character varying(100) NOT NULL DEFAULT 'Rotary International';

ALTER TABLE "Clubs" ADD "JourReunion" character varying(20) NOT NULL DEFAULT 'Mercredi';

ALTER TABLE "Clubs" ADD "HeureReunion" interval NOT NULL DEFAULT INTERVAL '18:30:00';

ALTER TABLE "Clubs" ADD "Frequence" character varying(50) NOT NULL DEFAULT 'Hebdomadaire';

ALTER TABLE "Clubs" ADD "Adresse" character varying(300) NOT NULL DEFAULT 'Adresse à définir';

UPDATE "Clubs" SET "Email" = '' WHERE "Email" IS NULL;
ALTER TABLE "Clubs" ALTER COLUMN "Email" SET NOT NULL;
ALTER TABLE "Clubs" ALTER COLUMN "Email" SET DEFAULT '';


                UPDATE "Clubs" 
                SET "NumeroClub" = 'RC' || LPAD(ROW_NUMBER() OVER (ORDER BY "Id")::text, 3, '0')
                WHERE "NumeroClub" = 'TEMP';
            


                UPDATE "Clubs" 
                SET "Email" = CASE 
                    WHEN "Email" = '' OR "Email" IS NULL 
                    THEN LOWER(REPLACE("Name", ' ', '')) || ROW_NUMBER() OVER (ORDER BY "Id") || '@club.rotary'
                    ELSE "Email"
                END
                WHERE "Email" = '' OR "Email" IS NULL;
            


                UPDATE "Clubs" 
                SET "Adresse" = COALESCE("Address", '') || 
                                CASE WHEN "City" IS NOT NULL AND "City" != '' 
                                     THEN ', ' || "City" 
                                     ELSE '' END ||
                                CASE WHEN "Country" IS NOT NULL AND "Country" != '' 
                                     THEN ', ' || "Country" 
                                     ELSE '' END
                WHERE "Adresse" = 'Adresse à définir' AND 
                      ("Address" IS NOT NULL OR "City" IS NOT NULL OR "Country" IS NOT NULL);
            


                UPDATE "Clubs" 
                SET "NumeroTelephone" = "PhoneNumber"
                WHERE "PhoneNumber" IS NOT NULL AND "PhoneNumber" != '' AND "NumeroTelephone" = '+0000000000';
            


                UPDATE "Clubs" 
                SET "Adresse" = 'Adresse à définir'
                WHERE "Adresse" = '' OR "Adresse" = ', ' OR "Adresse" = ', , ';
            

CREATE UNIQUE INDEX "IX_Clubs_NumeroClub" ON "Clubs" ("NumeroClub");

CREATE UNIQUE INDEX "IX_Clubs_Email" ON "Clubs" ("Email");

ALTER TABLE "Clubs" DROP COLUMN "Address";

ALTER TABLE "Clubs" DROP COLUMN "City";

ALTER TABLE "Clubs" DROP COLUMN "Code";

ALTER TABLE "Clubs" DROP COLUMN "Country";

ALTER TABLE "Clubs" DROP COLUMN "Description";

ALTER TABLE "Clubs" DROP COLUMN "FoundedDate";

ALTER TABLE "Clubs" DROP COLUMN "IsActive";

ALTER TABLE "Clubs" DROP COLUMN "LogoUrl";

ALTER TABLE "Clubs" DROP COLUMN "PhoneNumber";

ALTER TABLE "Clubs" DROP COLUMN "Website";

ALTER TABLE "Reunions" ADD "ClubId" uuid;

ALTER TABLE "PaiementCotisations" ADD "ClubId" uuid;

ALTER TABLE "Evenements" ADD "ClubId" uuid;

ALTER TABLE "Commissions" ADD "ClubId" uuid;

ALTER TABLE "Comites" ADD "ClubId" uuid;


                DO $$
                DECLARE
                    default_club_id UUID;
                BEGIN
                    -- Récupérer le premier club disponible
                    SELECT "Id" INTO default_club_id FROM "Clubs" LIMIT 1;
                    
                    IF default_club_id IS NOT NULL THEN
                        -- Mettre à jour toutes les tables
                        UPDATE "Comites" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                        UPDATE "Evenements" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                        UPDATE "Reunions" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                        UPDATE "Commissions" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                        UPDATE "PaiementCotisations" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                    ELSE
                        -- Créer un club par défaut si aucun n'existe
                        INSERT INTO "Clubs" ("Id", "Name", "DateCreation", "NumeroClub", "NumeroTelephone", "Email", "LieuReunion", "ParrainePar", "JourReunion", "HeureReunion", "Frequence", "Adresse")
                        VALUES (gen_random_uuid(), 'Club par défaut', '2024-01-01', 'RC000', '+0000000000', 'default@club.rotary', 'Lieu par défaut', 'Rotary International', 'Mercredi', INTERVAL '18:30:00', 'Hebdomadaire', 'Adresse par défaut');
                        
                        -- Récupérer l'ID du club créé
                        SELECT "Id" INTO default_club_id FROM "Clubs" WHERE "NumeroClub" = 'RC000';
                        
                        -- Mettre à jour toutes les tables
                        UPDATE "Comites" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                        UPDATE "Evenements" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                        UPDATE "Reunions" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                        UPDATE "Commissions" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                        UPDATE "PaiementCotisations" SET "ClubId" = default_club_id WHERE "ClubId" IS NULL;
                    END IF;
                END $$;
            

ALTER TABLE "Reunions" ALTER COLUMN "ClubId" SET NOT NULL;

ALTER TABLE "PaiementCotisations" ALTER COLUMN "ClubId" SET NOT NULL;

ALTER TABLE "Evenements" ALTER COLUMN "ClubId" SET NOT NULL;

ALTER TABLE "Commissions" ALTER COLUMN "ClubId" SET NOT NULL;

ALTER TABLE "Comites" ALTER COLUMN "ClubId" SET NOT NULL;

CREATE UNIQUE INDEX "IX_Reunion_ClubId_Date_Heure_TypeReunion_Unique" ON "Reunions" ("ClubId", "Date", "Heure", "TypeReunionId");

CREATE INDEX "IX_Reunions_ClubId" ON "Reunions" ("ClubId");

CREATE INDEX "IX_Reunions_ClubId_Date" ON "Reunions" ("ClubId", "Date");

CREATE INDEX "IX_Reunions_ClubId_Date_Heure" ON "Reunions" ("ClubId", "Date", "Heure");

CREATE INDEX "IX_Reunions_ClubId_TypeReunionId" ON "Reunions" ("ClubId", "TypeReunionId");

CREATE INDEX "IX_PaiementCotisations_ClubId" ON "PaiementCotisations" ("ClubId");

CREATE UNIQUE INDEX "IX_Evenement_ClubId_Libelle_Date_Unique" ON "Evenements" ("ClubId", "Libelle", "Date");

CREATE INDEX "IX_Evenements_ClubId" ON "Evenements" ("ClubId");

CREATE INDEX "IX_Evenements_ClubId_Date" ON "Evenements" ("ClubId", "Date");

CREATE INDEX "IX_Evenements_ClubId_Date_EstInterne" ON "Evenements" ("ClubId", "Date", "EstInterne");

CREATE INDEX "IX_Evenements_ClubId_EstInterne" ON "Evenements" ("ClubId", "EstInterne");

CREATE UNIQUE INDEX "IX_Commission_ClubId_Nom_Unique" ON "Commissions" ("ClubId", "Nom");

CREATE INDEX "IX_Commissions_ClubId" ON "Commissions" ("ClubId");

CREATE INDEX "IX_Commissions_Nom" ON "Commissions" ("Nom");

CREATE UNIQUE INDEX "IX_Comite_ClubId_MandatId_Nom_Unique" ON "Comites" ("ClubId", "MandatId", "Nom");

CREATE INDEX "IX_Comites_ClubId" ON "Comites" ("ClubId");

CREATE INDEX "IX_Comites_ClubId_MandatId" ON "Comites" ("ClubId", "MandatId");

CREATE INDEX "IX_Comites_Nom" ON "Comites" ("Nom");

ALTER TABLE "Comites" ADD CONSTRAINT "FK_Comites_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE;

ALTER TABLE "Commissions" ADD CONSTRAINT "FK_Commissions_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE;

ALTER TABLE "Evenements" ADD CONSTRAINT "FK_Evenements_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE;

ALTER TABLE "PaiementCotisations" ADD CONSTRAINT "FK_PaiementCotisations_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE;

ALTER TABLE "Reunions" ADD CONSTRAINT "FK_Reunions_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250530172812_club', '9.0.5');

CREATE TABLE "Categories" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(100) NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "FonctionEcheances" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(200) NOT NULL,
    "DateButoir" timestamp with time zone NOT NULL,
    "Frequence" integer NOT NULL,
    "FonctionId" uuid NOT NULL,
    CONSTRAINT "PK_FonctionEcheances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FonctionEcheances_Fonctions_FonctionId" FOREIGN KEY ("FonctionId") REFERENCES "Fonctions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "FonctionRolesResponsabilites" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "FonctionId" uuid NOT NULL,
    CONSTRAINT "PK_FonctionRolesResponsabilites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FonctionRolesResponsabilites_Fonctions_FonctionId" FOREIGN KEY ("FonctionId") REFERENCES "Fonctions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TypesBudget" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(50) NOT NULL,
    CONSTRAINT "PK_TypesBudget" PRIMARY KEY ("Id")
);

CREATE TABLE "TypesDocument" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(100) NOT NULL,
    CONSTRAINT "PK_TypesDocument" PRIMARY KEY ("Id")
);

CREATE TABLE "CategoriesBudget" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(100) NOT NULL,
    "TypeBudgetId" uuid NOT NULL,
    CONSTRAINT "PK_CategoriesBudget" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CategoriesBudget_TypesBudget_TypeBudgetId" FOREIGN KEY ("TypeBudgetId") REFERENCES "TypesBudget" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Documents" (
    "Id" uuid NOT NULL,
    "Nom" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "Fichier" bytea NOT NULL,
    "CategorieId" uuid NOT NULL,
    "TypeDocumentId" uuid NOT NULL,
    "ClubId" uuid NOT NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_Categories_CategorieId" FOREIGN KEY ("CategorieId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Documents_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Documents_TypesDocument_TypeDocumentId" FOREIGN KEY ("TypeDocumentId") REFERENCES "TypesDocument" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "SousCategoriesBudget" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(150) NOT NULL,
    "CategoryBudgetId" uuid NOT NULL,
    "ClubId" uuid NOT NULL,
    CONSTRAINT "PK_SousCategoriesBudget" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SousCategoriesBudget_CategoriesBudget_CategoryBudgetId" FOREIGN KEY ("CategoryBudgetId") REFERENCES "CategoriesBudget" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SousCategoriesBudget_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RubriquesBudget" (
    "Id" uuid NOT NULL,
    "Libelle" character varying(200) NOT NULL,
    "PrixUnitaire" numeric(18,2) NOT NULL,
    "Quantite" integer NOT NULL DEFAULT 1,
    "SousCategoryBudgetId" uuid NOT NULL,
    "MandatId" uuid NOT NULL,
    "ClubId" uuid NOT NULL,
    CONSTRAINT "PK_RubriquesBudget" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RubriquesBudget_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RubriquesBudget_Mandats_MandatId" FOREIGN KEY ("MandatId") REFERENCES "Mandats" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RubriquesBudget_SousCategoriesBudget_SousCategoryBudgetId" FOREIGN KEY ("SousCategoryBudgetId") REFERENCES "SousCategoriesBudget" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RubriquesBudgetRealisees" (
    "Id" uuid NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Montant" numeric(18,2) NOT NULL,
    "Commentaires" character varying(500),
    "RubriqueBudgetId" uuid NOT NULL,
    CONSTRAINT "PK_RubriquesBudgetRealisees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RubriquesBudgetRealisees_RubriquesBudget_RubriqueBudgetId" FOREIGN KEY ("RubriqueBudgetId") REFERENCES "RubriquesBudget" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Categorie_Libelle_Unique" ON "Categories" ("Libelle");

CREATE INDEX "IX_CategoriesBudget_Libelle" ON "CategoriesBudget" ("Libelle");

CREATE INDEX "IX_CategoriesBudget_TypeBudgetId" ON "CategoriesBudget" ("TypeBudgetId");

CREATE UNIQUE INDEX "IX_CategoryBudget_TypeBudgetId_Libelle_Unique" ON "CategoriesBudget" ("TypeBudgetId", "Libelle");

CREATE UNIQUE INDEX "IX_Document_ClubId_CategorieId_TypeDocumentId_Nom_Unique" ON "Documents" ("ClubId", "CategorieId", "TypeDocumentId", "Nom");

CREATE INDEX "IX_Documents_CategorieId" ON "Documents" ("CategorieId");

CREATE INDEX "IX_Documents_ClubId" ON "Documents" ("ClubId");

CREATE INDEX "IX_Documents_ClubId_CategorieId" ON "Documents" ("ClubId", "CategorieId");

CREATE INDEX "IX_Documents_ClubId_CategorieId_TypeDocumentId" ON "Documents" ("ClubId", "CategorieId", "TypeDocumentId");

CREATE INDEX "IX_Documents_ClubId_TypeDocumentId" ON "Documents" ("ClubId", "TypeDocumentId");

CREATE INDEX "IX_Documents_Nom" ON "Documents" ("Nom");

CREATE INDEX "IX_Documents_TypeDocumentId" ON "Documents" ("TypeDocumentId");

CREATE INDEX "IX_FonctionEcheances_DateButoir" ON "FonctionEcheances" ("DateButoir");

CREATE INDEX "IX_FonctionEcheances_DateButoir_Frequence" ON "FonctionEcheances" ("DateButoir", "Frequence");

CREATE INDEX "IX_FonctionEcheances_FonctionId" ON "FonctionEcheances" ("FonctionId");

CREATE INDEX "IX_FonctionEcheances_FonctionId_DateButoir" ON "FonctionEcheances" ("FonctionId", "DateButoir");

CREATE INDEX "IX_FonctionEcheances_FonctionId_Frequence" ON "FonctionEcheances" ("FonctionId", "Frequence");

CREATE UNIQUE INDEX "IX_FonctionEcheances_FonctionId_Libelle_Unique" ON "FonctionEcheances" ("FonctionId", "Libelle");

CREATE INDEX "IX_FonctionEcheances_Frequence" ON "FonctionEcheances" ("Frequence");

CREATE INDEX "IX_FonctionEcheances_Libelle" ON "FonctionEcheances" ("Libelle");

CREATE INDEX "IX_FonctionRolesResponsabilites_FonctionId" ON "FonctionRolesResponsabilites" ("FonctionId");

CREATE UNIQUE INDEX "IX_FonctionRolesResponsabilites_FonctionId_Libelle_Unique" ON "FonctionRolesResponsabilites" ("FonctionId", "Libelle");

CREATE INDEX "IX_FonctionRolesResponsabilites_Libelle" ON "FonctionRolesResponsabilites" ("Libelle");

CREATE UNIQUE INDEX "IX_RubriqueBudget_ClubId_MandatId_SousCategoryBudgetId_Libelle_Unique" ON "RubriquesBudget" ("ClubId", "MandatId", "SousCategoryBudgetId", "Libelle");

CREATE INDEX "IX_RubriquesBudget_ClubId" ON "RubriquesBudget" ("ClubId");

CREATE INDEX "IX_RubriquesBudget_ClubId_MandatId" ON "RubriquesBudget" ("ClubId", "MandatId");

CREATE INDEX "IX_RubriquesBudget_ClubId_MandatId_SousCategoryBudgetId" ON "RubriquesBudget" ("ClubId", "MandatId", "SousCategoryBudgetId");

CREATE INDEX "IX_RubriquesBudget_ClubId_SousCategoryBudgetId" ON "RubriquesBudget" ("ClubId", "SousCategoryBudgetId");

CREATE INDEX "IX_RubriquesBudget_Libelle" ON "RubriquesBudget" ("Libelle");

CREATE INDEX "IX_RubriquesBudget_MandatId" ON "RubriquesBudget" ("MandatId");

CREATE INDEX "IX_RubriquesBudget_PrixUnitaire" ON "RubriquesBudget" ("PrixUnitaire");

CREATE INDEX "IX_RubriquesBudget_SousCategoryBudgetId" ON "RubriquesBudget" ("SousCategoryBudgetId");

CREATE INDEX "IX_RubriquesBudgetRealisees_Date" ON "RubriquesBudgetRealisees" ("Date");

CREATE INDEX "IX_RubriquesBudgetRealisees_Montant" ON "RubriquesBudgetRealisees" ("Montant");

CREATE INDEX "IX_RubriquesBudgetRealisees_RubriqueBudgetId" ON "RubriquesBudgetRealisees" ("RubriqueBudgetId");

CREATE INDEX "IX_RubriquesBudgetRealisees_RubriqueBudgetId_Date" ON "RubriquesBudgetRealisees" ("RubriqueBudgetId", "Date");

CREATE INDEX "IX_RubriquesBudgetRealisees_RubriqueBudgetId_Date_Montant" ON "RubriquesBudgetRealisees" ("RubriqueBudgetId", "Date", "Montant");

CREATE INDEX "IX_SousCategoriesBudget_CategoryBudgetId" ON "SousCategoriesBudget" ("CategoryBudgetId");

CREATE INDEX "IX_SousCategoriesBudget_ClubId" ON "SousCategoriesBudget" ("ClubId");

CREATE INDEX "IX_SousCategoriesBudget_ClubId_CategoryBudgetId" ON "SousCategoriesBudget" ("ClubId", "CategoryBudgetId");

CREATE INDEX "IX_SousCategoriesBudget_Libelle" ON "SousCategoriesBudget" ("Libelle");

CREATE UNIQUE INDEX "IX_SousCategoryBudget_ClubId_CategoryBudgetId_Libelle_Unique" ON "SousCategoriesBudget" ("ClubId", "CategoryBudgetId", "Libelle");

CREATE UNIQUE INDEX "IX_TypeBudget_Libelle_Unique" ON "TypesBudget" ("Libelle");

CREATE UNIQUE INDEX "IX_TypeDocument_Libelle_Unique" ON "TypesDocument" ("Libelle");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250530190116_GestionDocumentsEtBudget', '9.0.5');

ALTER TABLE "MembresCommission" DROP CONSTRAINT "FK_MembresCommission_AspNetUsers_ApplicationUserId";

DROP INDEX "IX_MembresCommission_ApplicationUserId";

ALTER TABLE "MembresCommission" DROP COLUMN "ApplicationUserId";

ALTER INDEX "IX_MembresCommission_CommissionId_MembreId_MandatId" RENAME TO "IX_MembreCommission_Commission_Membre_Mandat_Unique";

CREATE INDEX "IX_MembresCommission_CommissionId" ON "MembresCommission" ("CommissionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250531205625_CommissionMembre1', '9.0.5');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250531225626_FixMembreCommissionFinal', '9.0.5');


                DO $$ 
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.table_constraints 
                        WHERE constraint_name = 'FK_MembresCommission_CommissionClub_CommissionClubId'
                        AND table_name = 'MembresCommission'
                    ) THEN
                        ALTER TABLE "MembresCommission" DROP CONSTRAINT "FK_MembresCommission_CommissionClub_CommissionClubId";
                    END IF;
                END $$;
            


                DO $$ 
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'IX_MembresCommission_CommissionClubId'
                        AND tablename = 'MembresCommission'
                    ) THEN
                        DROP INDEX "IX_MembresCommission_CommissionClubId";
                    END IF;
                END $$;
            


                DO $$ 
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'MembresCommission' 
                        AND column_name = 'CommissionClubId'
                    ) THEN
                        ALTER TABLE "MembresCommission" DROP COLUMN "CommissionClubId";
                    END IF;
                END $$;
            


                DO $$ 
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'CommissionClub'
                    ) THEN
                        DROP TABLE "CommissionClub";
                    END IF;
                END $$;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250531231147_FixMembreCommissionFinal1', '9.0.5');

ALTER TABLE "Mandats" ADD "Comite" text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250603172042_Mandat', '9.0.5');

ALTER TABLE "ComiteMembres" DROP CONSTRAINT "FK_ComiteMembres_Comites_ComiteId";

ALTER TABLE "ComiteMembres" RENAME COLUMN "ComiteId" TO "MandatId";

ALTER INDEX "IX_ComiteMembres_ComiteId_MembreId_FonctionId" RENAME TO "IX_ComiteMembres_MandatId_MembreId_FonctionId";

ALTER TABLE "Mandats" ALTER COLUMN "Comite" TYPE character varying(100);

ALTER TABLE "ComiteMembres" ADD CONSTRAINT "FK_ComiteMembres_Mandats_MandatId" FOREIGN KEY ("MandatId") REFERENCES "Mandats" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250603181737_ComiteMembre', '9.0.5');

ALTER TABLE "Fonctions" ADD "ParentId" uuid;

CREATE INDEX "IX_Fonctions_ParentId" ON "Fonctions" ("ParentId");

ALTER TABLE "Fonctions" ADD CONSTRAINT "FK_Fonctions_Fonctions_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Fonctions" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250603234029_Fonction', '9.0.5');

ALTER TABLE "Fonctions" DROP CONSTRAINT "FK_Fonctions_Fonctions_ParentId";

DROP INDEX "IX_Fonctions_NomFonction";

DROP INDEX "IX_Fonctions_ParentId";

ALTER TABLE "Fonctions" DROP COLUMN "ParentId";

CREATE UNIQUE INDEX "IX_Fonctions_NomFonction" ON "Fonctions" ("NomFonction");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250605070445_Fonction1', '9.0.5');

CREATE TABLE "Galas" (
    "Id" uuid NOT NULL,
    "Libelle" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Lieu" text NOT NULL,
    "NombreTables" integer NOT NULL,
    "NombreSouchesTickets" integer NOT NULL,
    "QuantiteParSoucheTickets" integer NOT NULL,
    "NombreSouchesTombola" integer NOT NULL,
    "QuantiteParSoucheTombola" integer NOT NULL,
    CONSTRAINT "PK_Galas" PRIMARY KEY ("Id")
);

CREATE TABLE "GalaInvites" (
    "Id" uuid NOT NULL,
    "Nom_Prenom" text NOT NULL,
    "GalaId" uuid NOT NULL,
    CONSTRAINT "PK_GalaInvites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GalaInvites_Galas_GalaId" FOREIGN KEY ("GalaId") REFERENCES "Galas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GalaTables" (
    "Id" uuid NOT NULL,
    "TableLibelle" text NOT NULL,
    "GalaId" uuid NOT NULL,
    CONSTRAINT "PK_GalaTables" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GalaTables_Galas_GalaId" FOREIGN KEY ("GalaId") REFERENCES "Galas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GalaTickets" (
    "Id" uuid NOT NULL,
    "Quantite" integer NOT NULL,
    "GalaId" uuid NOT NULL,
    "MembreId" text NOT NULL,
    CONSTRAINT "PK_GalaTickets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GalaTickets_AspNetUsers_MembreId" FOREIGN KEY ("MembreId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_GalaTickets_Galas_GalaId" FOREIGN KEY ("GalaId") REFERENCES "Galas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GalaTombolas" (
    "Id" uuid NOT NULL,
    "Quantite" integer NOT NULL,
    "GalaId" uuid NOT NULL,
    "MembreId" text NOT NULL,
    CONSTRAINT "PK_GalaTombolas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GalaTombolas_AspNetUsers_MembreId" FOREIGN KEY ("MembreId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_GalaTombolas_Galas_GalaId" FOREIGN KEY ("GalaId") REFERENCES "Galas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GalaTableAffectations" (
    "Id" uuid NOT NULL,
    "GalaTableId" uuid NOT NULL,
    "GalaInvitesId" uuid NOT NULL,
    CONSTRAINT "PK_GalaTableAffectations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GalaTableAffectations_GalaInvites_GalaInvitesId" FOREIGN KEY ("GalaInvitesId") REFERENCES "GalaInvites" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GalaTableAffectations_GalaTables_GalaTableId" FOREIGN KEY ("GalaTableId") REFERENCES "GalaTables" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_GalaInvites_GalaId" ON "GalaInvites" ("GalaId");

CREATE UNIQUE INDEX "IX_GalaTableAffectation_GalaTableId_GalaInvitesId_Unique" ON "GalaTableAffectations" ("GalaTableId", "GalaInvitesId");

CREATE INDEX "IX_GalaTableAffectations_GalaInvitesId" ON "GalaTableAffectations" ("GalaInvitesId");

CREATE INDEX "IX_GalaTableAffectations_GalaTableId" ON "GalaTableAffectations" ("GalaTableId");

CREATE INDEX "IX_GalaTables_GalaId" ON "GalaTables" ("GalaId");

CREATE UNIQUE INDEX "IX_GalaTicket_GalaId_MembreId_Unique" ON "GalaTickets" ("GalaId", "MembreId");

CREATE INDEX "IX_GalaTickets_GalaId" ON "GalaTickets" ("GalaId");

CREATE INDEX "IX_GalaTickets_MembreId" ON "GalaTickets" ("MembreId");

CREATE INDEX "IX_GalaTickets_Quantite" ON "GalaTickets" ("Quantite");

CREATE UNIQUE INDEX "IX_GalaTombola_GalaId_MembreId_Unique" ON "GalaTombolas" ("GalaId", "MembreId");

CREATE INDEX "IX_GalaTombolas_GalaId" ON "GalaTombolas" ("GalaId");

CREATE INDEX "IX_GalaTombolas_MembreId" ON "GalaTombolas" ("MembreId");

CREATE INDEX "IX_GalaTombolas_Quantite" ON "GalaTombolas" ("Quantite");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250606195512_GestionGala', '9.0.5');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250606215341_GestionGala1', '9.0.5');

DROP INDEX "IX_GalaTombola_GalaId_MembreId_Unique";

ALTER TABLE "GalaTombolas" DROP CONSTRAINT "CK_GalaTombola_MembreOrExterne";

DROP INDEX "IX_GalaTicket_GalaId_MembreId_Unique";

ALTER TABLE "GalaTickets" DROP CONSTRAINT "CK_GalaTicket_MembreOrExterne";

CREATE UNIQUE INDEX "IX_GalaTombola_GalaId_MembreId_Unique" ON "GalaTombolas" ("GalaId", "MembreId") WHERE "MembreId" IS NOT NULL;

ALTER TABLE "GalaTombolas" ADD CONSTRAINT "CK_GalaTombola_MembreOrExterne" CHECK (("MembreId" IS NOT NULL) OR ("Externe" IS NOT NULL AND "Externe" != ''));

CREATE UNIQUE INDEX "IX_GalaTicket_GalaId_MembreId_Unique" ON "GalaTickets" ("GalaId", "MembreId") WHERE "MembreId" IS NOT NULL;

ALTER TABLE "GalaTickets" ADD CONSTRAINT "CK_GalaTicket_MembreOrExterne" CHECK (("MembreId" IS NOT NULL) OR ("Externe" IS NOT NULL AND "Externe" != ''));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250609102953_GestionGala121', '9.0.5');

ALTER INDEX "IX_GalaTableAffectations_GalaTableId" RENAME TO "IX_GalaTableAffectation_GalaTableId";

ALTER INDEX "IX_GalaTableAffectations_GalaInvitesId" RENAME TO "IX_GalaTableAffectation_GalaInvitesId";

ALTER TABLE "GalaTableAffectations" ADD "DateAjout" timestamp with time zone NOT NULL DEFAULT (NOW());

CREATE INDEX "IX_GalaTableAffectation_DateAjout" ON "GalaTableAffectations" ("DateAjout");

CREATE INDEX "IX_GalaTableAffectation_DateAjout_GalaTableId" ON "GalaTableAffectations" ("DateAjout", "GalaTableId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250610170708_GestionGala122', '9.0.5');

CREATE TABLE "OrdreJourRapports" (
    "Id" uuid NOT NULL,
    "OrdreDuJourId" uuid NOT NULL,
    "Texte" text NOT NULL,
    "Divers" text,
    CONSTRAINT "PK_OrdreJourRapports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrdreJourRapports_OrdresDuJour_OrdreDuJourId" FOREIGN KEY ("OrdreDuJourId") REFERENCES "OrdresDuJour" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_OrdreJourRapports_OrdreDuJourId" ON "OrdreJourRapports" ("OrdreDuJourId");

CREATE INDEX "IX_OrdreJourRapports_OrdreDuJourId_Texte" ON "OrdreJourRapports" ("OrdreDuJourId", "Texte");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250619095834_AddOrdreJourRapportTable', '9.0.5');

CREATE TABLE "RotaryClubs" (
    "Id" uuid NOT NULL,
    "ClubId" uuid NOT NULL,
    "NumeroClub" text NOT NULL,
    "NumeroTelephone" text NOT NULL,
    "Email" text NOT NULL,
    "LieuReunion" text NOT NULL,
    "ParrainePar" text NOT NULL,
    "JourReunion" text NOT NULL,
    "HeureReunion" time NOT NULL,
    "Frequence" text NOT NULL,
    "Adresse" text NOT NULL,
    CONSTRAINT "PK_RotaryClubs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RotaryClubs_Clubs_ClubId" FOREIGN KEY ("ClubId") REFERENCES "Clubs" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_RotaryClubs_ClubId" ON "RotaryClubs" ("ClubId");

CREATE INDEX "IX_RotaryClubs_Email" ON "RotaryClubs" ("Email");

CREATE INDEX "IX_RotaryClubs_JourReunion" ON "RotaryClubs" ("JourReunion");

CREATE UNIQUE INDEX "IX_RotaryClubs_NumeroClub" ON "RotaryClubs" ("NumeroClub");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250619111620_AddRotaryClubTable', '9.0.5');

DROP TABLE "RotaryClubs";

DROP INDEX "IX_Clubs_Code";

ALTER TABLE "Clubs" DROP COLUMN "Address";

ALTER TABLE "Clubs" DROP COLUMN "City";

ALTER TABLE "Clubs" DROP COLUMN "Code";

ALTER TABLE "Clubs" DROP COLUMN "Country";

ALTER TABLE "Clubs" DROP COLUMN "Description";

ALTER TABLE "Clubs" DROP COLUMN "FoundedDate";

ALTER TABLE "Clubs" DROP COLUMN "IsActive";

ALTER TABLE "Clubs" DROP COLUMN "LogoUrl";

ALTER TABLE "Clubs" DROP COLUMN "PhoneNumber";

ALTER TABLE "Clubs" DROP COLUMN "Website";

UPDATE "Clubs" SET "Email" = '' WHERE "Email" IS NULL;
ALTER TABLE "Clubs" ALTER COLUMN "Email" SET NOT NULL;
ALTER TABLE "Clubs" ALTER COLUMN "Email" SET DEFAULT '';

ALTER TABLE "Clubs" ADD "Adresse" character varying(300) NOT NULL DEFAULT '';

ALTER TABLE "Clubs" ADD "DateCreation" character varying(50) NOT NULL DEFAULT '';

ALTER TABLE "Clubs" ADD "Frequence" character varying(50) NOT NULL DEFAULT '';

ALTER TABLE "Clubs" ADD "HeureReunion" interval NOT NULL DEFAULT INTERVAL '00:00:00';

ALTER TABLE "Clubs" ADD "JourReunion" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE "Clubs" ADD "LieuReunion" character varying(200) NOT NULL DEFAULT '';

ALTER TABLE "Clubs" ADD "NumeroClub" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE "Clubs" ADD "NumeroTelephone" character varying(20) NOT NULL DEFAULT '';

ALTER TABLE "Clubs" ADD "ParrainePar" character varying(100) NOT NULL DEFAULT '';

CREATE UNIQUE INDEX "IX_Clubs_Email" ON "Clubs" ("Email");

CREATE UNIQUE INDEX "IX_Clubs_NumeroClub" ON "Clubs" ("NumeroClub");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250619232002_UpdateClubEntity', '9.0.5');

ALTER TABLE "Clubs" ALTER COLUMN "NumeroClub" TYPE integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250620000919_ConvertNumeroClubToInt', '9.0.5');

ALTER TABLE "Clubs" ALTER COLUMN "ParrainePar" DROP NOT NULL;

ALTER TABLE "Clubs" ALTER COLUMN "NumeroTelephone" DROP NOT NULL;

ALTER TABLE "Clubs" ALTER COLUMN "NumeroClub" DROP NOT NULL;

ALTER TABLE "Clubs" ALTER COLUMN "LieuReunion" DROP NOT NULL;

ALTER TABLE "Clubs" ALTER COLUMN "JourReunion" DROP NOT NULL;

ALTER TABLE "Clubs" ALTER COLUMN "HeureReunion" DROP NOT NULL;

ALTER TABLE "Clubs" ALTER COLUMN "Frequence" DROP NOT NULL;

ALTER TABLE "Clubs" ALTER COLUMN "Email" DROP NOT NULL;

ALTER TABLE "Clubs" ALTER COLUMN "DateCreation" DROP NOT NULL;

ALTER TABLE "Clubs" ALTER COLUMN "Adresse" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250620025526_MakeClubFieldsOptional', '9.0.5');

COMMIT;

