// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RotaryClubManager.Infrastructure.Data;

#nullable disable

namespace RotaryClubManager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250528162926_Evenement")]
    partial class Evenement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FoundedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Comite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MandatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MandatId");

                    b.ToTable("Comites");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.ComiteMembre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComiteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FonctionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FonctionId");

                    b.HasIndex("MembreId");

                    b.HasIndex("ComiteId", "MembreId", "FonctionId")
                        .IsUnique();

                    b.ToTable("ComiteMembres");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Commissions");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.CommissionClub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NotesSpecifiques")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("CommissionId", "ClubId")
                        .IsUnique();

                    b.ToTable("CommissionsClub");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Cotisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MandatId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Montant")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MandatId");

                    b.HasIndex("MembreId");

                    b.HasIndex("Montant");

                    b.HasIndex("MembreId", "MandatId")
                        .IsUnique();

                    b.ToTable("Cotisations");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Evenement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("EstInterne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Lieu")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EstInterne");

                    b.HasIndex("Libelle");

                    b.HasIndex("Date", "EstInterne");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.EvenementBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("MontantBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontantRealise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.HasIndex("Libelle");

                    b.HasIndex("MontantBudget");

                    b.HasIndex("EvenementId", "Libelle")
                        .IsUnique()
                        .HasDatabaseName("IX_EvenementBudget_EvenementId_Libelle_Unique");

                    b.ToTable("EvenementBudgets");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.EvenementDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAjout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("Document")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DateAjout");

                    b.HasIndex("EvenementId");

                    b.HasIndex("Libelle");

                    b.HasIndex("EvenementId", "Libelle")
                        .IsUnique()
                        .HasDatabaseName("IX_EvenementDocument_EvenementId_Libelle_Unique");

                    b.ToTable("EvenementDocuments");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.EvenementImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAjout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("DateAjout");

                    b.HasIndex("Description");

                    b.HasIndex("EvenementId");

                    b.ToTable("EvenementImages");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.EvenementRecette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.HasIndex("Libelle");

                    b.HasIndex("Montant");

                    b.ToTable("EvenementRecettes");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Fonction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NomFonction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NomFonction");

                    b.ToTable("Fonctions");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.InviteReunion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ReunionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ReunionId");

                    b.HasIndex("Nom", "Prenom");

                    b.ToTable("InvitesReunion");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.ListePresence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MembreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReunionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MembreId");

                    b.HasIndex("ReunionId");

                    b.HasIndex("MembreId", "ReunionId")
                        .IsUnique();

                    b.ToTable("ListesPresence");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Mandat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Annee")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EstActuel")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Annee")
                        .IsUnique();

                    b.HasIndex("ClubId", "EstActuel")
                        .IsUnique()
                        .HasFilter("EstActuel = 1");

                    b.ToTable("Mandats");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.MembreCommission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("Commentaires")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CommissionClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateDemission")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateNomination")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstResponsable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MandatId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("MandatId");

                    b.HasIndex("MembreId");

                    b.HasIndex("CommissionClubId", "MembreId", "MandatId")
                        .IsUnique();

                    b.ToTable("MembresCommission");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.OrdreDuJour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ReunionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReunionId");

                    b.ToTable("OrdresDuJour");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.PaiementCotisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaires")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp");

                    b.Property<string>("MembreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Montant")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MembreId");

                    b.HasIndex("Montant");

                    b.HasIndex("MembreId", "Date");

                    b.ToTable("PaiementCotisations");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Reunion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("Heure")
                        .HasColumnType("time");

                    b.Property<Guid>("TypeReunionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypeReunionId");

                    b.HasIndex("Date", "Heure");

                    b.ToTable("Reunions");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.ReunionDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Document")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ReunionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Libelle");

                    b.HasIndex("ReunionId");

                    b.HasIndex("ReunionId", "Libelle")
                        .IsUnique()
                        .HasDatabaseName("IX_ReunionDocument_ReunionId_Libelle_Unique");

                    b.ToTable("ReunionDocuments");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.TypeReunion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Libelle")
                        .IsUnique();

                    b.ToTable("TypesReunion");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Identity.UserClub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClubs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Comite", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Mandat", "Mandat")
                        .WithMany()
                        .HasForeignKey("MandatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandat");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.ComiteMembre", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Comite", "Comite")
                        .WithMany()
                        .HasForeignKey("ComiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotaryClubManager.Domain.Entities.Fonction", "Fonction")
                        .WithMany()
                        .HasForeignKey("FonctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comite");

                    b.Navigation("Fonction");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.CommissionClub", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Club", "Club")
                        .WithMany("CommissionsClub")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotaryClubManager.Domain.Entities.Commission", "Commission")
                        .WithMany("CommissionsClub")
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Commission");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Cotisation", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Mandat", "Mandat")
                        .WithMany()
                        .HasForeignKey("MandatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mandat");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.EvenementBudget", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Evenement", "Evenement")
                        .WithMany("Budgets")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.EvenementDocument", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Evenement", "Evenement")
                        .WithMany("Documents")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.EvenementImage", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Evenement", "Evenement")
                        .WithMany("Images")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.EvenementRecette", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Evenement", "Evenement")
                        .WithMany("Recettes")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.InviteReunion", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Reunion", "Reunion")
                        .WithMany("Invites")
                        .HasForeignKey("ReunionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reunion");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.ListePresence", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RotaryClubManager.Domain.Entities.Reunion", "Reunion")
                        .WithMany("ListesPresence")
                        .HasForeignKey("ReunionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");

                    b.Navigation("Reunion");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Mandat", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Club", "Club")
                        .WithMany("Mandats")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.MembreCommission", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", null)
                        .WithMany("MembresCommission")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("RotaryClubManager.Domain.Entities.CommissionClub", "CommissionClub")
                        .WithMany("MembresCommission")
                        .HasForeignKey("CommissionClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotaryClubManager.Domain.Entities.Mandat", "Mandat")
                        .WithMany("MembresCommission")
                        .HasForeignKey("MandatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommissionClub");

                    b.Navigation("Mandat");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.OrdreDuJour", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Reunion", "Reunion")
                        .WithMany("OrdresDuJour")
                        .HasForeignKey("ReunionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reunion");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.PaiementCotisation", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Reunion", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.TypeReunion", "TypeReunion")
                        .WithMany("Reunions")
                        .HasForeignKey("TypeReunionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TypeReunion");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.ReunionDocument", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Reunion", "Reunion")
                        .WithMany("Documents")
                        .HasForeignKey("ReunionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reunion");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Identity.ApplicationUser", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Club", null)
                        .WithMany("Membres")
                        .HasForeignKey("ClubId");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Identity.UserClub", b =>
                {
                    b.HasOne("RotaryClubManager.Domain.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotaryClubManager.Domain.Identity.ApplicationUser", "User")
                        .WithMany("UserClubs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Club", b =>
                {
                    b.Navigation("CommissionsClub");

                    b.Navigation("Mandats");

                    b.Navigation("Membres");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Commission", b =>
                {
                    b.Navigation("CommissionsClub");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.CommissionClub", b =>
                {
                    b.Navigation("MembresCommission");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Evenement", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Documents");

                    b.Navigation("Images");

                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Mandat", b =>
                {
                    b.Navigation("MembresCommission");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.Reunion", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Invites");

                    b.Navigation("ListesPresence");

                    b.Navigation("OrdresDuJour");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Entities.TypeReunion", b =>
                {
                    b.Navigation("Reunions");
                });

            modelBuilder.Entity("RotaryClubManager.Domain.Identity.ApplicationUser", b =>
                {
                    b.Navigation("MembresCommission");

                    b.Navigation("UserClubs");
                });
#pragma warning restore 612, 618
        }
    }
}
